# Generated by Django 4.1.3 on 2022-11-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='historicalbook',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical book', 'verbose_name_plural': 'historical books'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='bookloan',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='book'),
        ),
        migrations.AddField(
            model_name='bookloan',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='book.author', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='book.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='historicalbookloan',
            name='book',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='book.book', verbose_name='book'),
        ),
        migrations.AddField(
            model_name='historicalbookloan',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='book.partner', verbose_name='Partner'),
        ),
    ]
